#!/usr/bin/env Rscript
# Snapshot the R-visible API surface of the `bw` package.
#
# Run via: ./tests/parity/verify_parity.sh    (which calls this inside Docker)
#
# Writes a deterministic, human-readable, diffable text dump to
# tests/parity/api_surface/exports.txt containing:
#   - the package name and version
#   - the sorted list of exported names
#   - the full signature (formals + default values) of every exported function
#   - any S3 / S4 method dispatch
#
# This file is the bit-level contract for the R API. Any change that alters
# function names, argument names, argument order, default values, or
# exported surface trips the parity gate. See docs/QA_R_BEHAVIOR_UNCHANGED.md.

suppressPackageStartupMessages(library(bw))

if (!exists("outdir")) outdir <- "tests/parity/api_surface"
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

pkg <- "bw"
ns <- asNamespace(pkg)

# --- helpers ---------------------------------------------------------------

# Render a function's signature as plain text.
# Uses base::args(), which returns a function shell with the same formals
# but no body — safely deparseable even when defaults are missing or contain
# unevaluated expressions. This avoids the `fmls[[i]]` trap that triggers
# "missing argument" errors on formals without defaults.
render_signature <- function(name) {
  fn <- tryCatch(get(name, envir = ns), error = function(e) NULL)
  if (is.null(fn) || !is.function(fn)) {
    return(paste0(name, "  <not exported as a function>"))
  }
  a <- args(fn)
  if (is.null(a)) return(paste0(name, "()"))
  s <- paste(deparse(a, width.cutoff = 500L), collapse = " ")
  # `args()` produces "function (bw, ht, age, sex, ...) NULL"
  # rewrite as "name(bw, ht, age, sex, ...)"
  s <- sub("^function ?", name, s)
  s <- sub(" *NULL *$", "", s)
  # Collapse runs of whitespace introduced by deparse line continuations.
  s <- gsub("[[:space:]]+", " ", s)
  s
}

# --- collect ---------------------------------------------------------------

desc       <- packageDescription(pkg)
pkg_version <- as.character(desc$Version)
pkg_title   <- as.character(desc$Title)

exports <- sort(getNamespaceExports(pkg))

s3_methods <- tryCatch(
  ls(envir = .getNamespaceInfo(ns, "S3methods")),
  error = function(e) character(0)
)
s3_methods <- sort(s3_methods)

s4_classes <- tryCatch(getClasses(ns, FALSE), error = function(e) character(0))
s4_classes <- sort(s4_classes)

# --- emit ------------------------------------------------------------------

out <- character()
out <- c(out, "# bw R package — API surface snapshot")
out <- c(out, "# Generated by tests/parity/snapshot_api.R")
out <- c(out, "# Diffed byte-for-byte against tests/parity/api_surface/exports.txt")
out <- c(out, "# by tests/parity/verify_parity.sh. Do not hand-edit.")
out <- c(out, "")
out <- c(out, "[package]")
out <- c(out, paste0("name    = ", pkg))
out <- c(out, paste0("version = ", pkg_version))
out <- c(out, paste0("title   = ", pkg_title))
out <- c(out, "")
out <- c(out, paste0("[exports]  (", length(exports), ")"))
for (e in exports) {
  out <- c(out, paste0("  ", e))
}
out <- c(out, "")

out <- c(out, "[function signatures]")
for (e in exports) {
  out <- c(out, paste0("  ", render_signature(e)))
}
out <- c(out, "")

if (length(s3_methods)) {
  out <- c(out, paste0("[S3 methods]  (", length(s3_methods), ")"))
  for (m in s3_methods) out <- c(out, paste0("  ", m))
  out <- c(out, "")
}

if (length(s4_classes)) {
  out <- c(out, paste0("[S4 classes]  (", length(s4_classes), ")"))
  for (c in s4_classes) out <- c(out, paste0("  ", c))
  out <- c(out, "")
}

# Always write with LF line endings, no trailing whitespace.
writeLines(out, con = file.path(outdir, "exports.txt"), sep = "\n")

cat(sprintf("Wrote API surface snapshot to %s/exports.txt (%d exports, %d S3 methods, %d S4 classes)\n",
            outdir, length(exports), length(s3_methods), length(s4_classes)))
