# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adult_weight_wrapper <- function(bw, ht, age, sex, EIchange, NAchange, PAL, pcarb_base, pcarb, dt, days, checkValues) {
    .Call('_bw_adult_weight_wrapper', PACKAGE = 'bw', bw, ht, age, sex, EIchange, NAchange, PAL, pcarb_base, pcarb, dt, days, checkValues)
}

adult_weight_wrapper_EI <- function(bw, ht, age, sex, EIchange, NAchange, PAL, pcarb_base, pcarb, dt, extradata, days, checkValues, isEnergy) {
    .Call('_bw_adult_weight_wrapper_EI', PACKAGE = 'bw', bw, ht, age, sex, EIchange, NAchange, PAL, pcarb_base, pcarb, dt, extradata, days, checkValues, isEnergy)
}

adult_weight_wrapper_EI_fat <- function(bw, ht, age, sex, EIchange, NAchange, PAL, pcarb_base, pcarb, dt, input_EI, input_fat, days, checkValues) {
    .Call('_bw_adult_weight_wrapper_EI_fat', PACKAGE = 'bw', bw, ht, age, sex, EIchange, NAchange, PAL, pcarb_base, pcarb, dt, input_EI, input_fat, days, checkValues)
}

child_weight_wrapper <- function(age, sex, FFM, FM, input_EIntake, days, dt, checkValues) {
    .Call('_bw_child_weight_wrapper', PACKAGE = 'bw', age, sex, FFM, FM, input_EIntake, days, dt, checkValues)
}

child_weight_wrapper_richardson <- function(age, sex, FFM, FM, K, Q, A, B, nu, C, days, dt, checkValues) {
    .Call('_bw_child_weight_wrapper_richardson', PACKAGE = 'bw', age, sex, FFM, FM, K, Q, A, B, nu, C, days, dt, checkValues)
}

intake_reference_wrapper <- function(age, sex, FFM, FM, days, dt) {
    .Call('_bw_intake_reference_wrapper', PACKAGE = 'bw', age, sex, FFM, FM, days, dt)
}

mass_reference_wrapper <- function(age, sex) {
    .Call('_bw_mass_reference_wrapper', PACKAGE = 'bw', age, sex)
}

EnergyBuilder <- function(Energy, Time, interpol) {
    .Call('_bw_EnergyBuilder', PACKAGE = 'bw', Energy, Time, interpol)
}

